# Computergestützte Mathematik zur Analysis

Vorlesung vom 10.11.2022

&copy; 2022 Prof. Dr. Rüdiger W. Braun 

In [1]:
from sympy import *

# Listen und Arrays

In [2]:
l = [1,2,3]
m = [4,5,6]
l

[1, 2, 3]

In [3]:
l.append(16)
l

[1, 2, 3, 16]

In [4]:
l[0]

1

In [5]:
l[1]

2

In [6]:
l[-1]  # letztes Element

16

In [7]:
len(l)

4

In [8]:
del l[2]

In [9]:
l

[1, 2, 16]

In [10]:
import numpy as np

In [11]:
a = np.array(l)
b = np.array(m)
a

array([ 1,  2, 16])

In [12]:
l + m

[1, 2, 16, 4, 5, 6]

In [15]:
a

array([ 1,  2, 16])

In [13]:
a + b

array([ 5,  7, 22])

In [16]:
l[1] = Rational(1,3)
l

[1, 1/3, 16]

In [17]:
init_printing()
l

In [18]:
a[1] = Rational(1,3)

In [19]:
a

array([ 1,  0, 16])

Aha ????

In [20]:
type(a)

numpy.ndarray

In [21]:
a.dtype

dtype('int32')

Ein `array` erhält den `dtype`, wenn die ersten Elemente hineingeschrieben werden.  Danach ist der `dtype` unveränderlich.

In [22]:
l + m

In [23]:
a + b

array([ 5,  5, 22])

# Schleifen

In [24]:
list(range(10))

In [26]:
for j in range(10):
    print(factorial(j)/2**j)
print("huhu")

1
1/2
1/2
3/4
3/2
15/4
45/4
315/8
315/2
2835/4
huhu


In [27]:
for j in range(10):
    display(factorial(2*j)/factorial(j)**3)

In [28]:
for p in range(-3,3):
    for q in range(1, 4):
        print(f"p={p}, q={q}")   # f-String
        display(Rational(p,q))

p=-3, q=1


p=-3, q=2


p=-3, q=3


p=-2, q=1


p=-2, q=2


p=-2, q=3


p=-1, q=1


p=-1, q=2


p=-1, q=3


p=0, q=1


p=0, q=2


p=0, q=3


p=1, q=1


p=1, q=2


p=1, q=3


p=2, q=1


p=2, q=2


p=2, q=3


In [29]:
m = 20
summe = 0
for n in range(1, m):
    summe += Rational(1,n)
summe

# Nochmal zurück zu `N`

In [30]:
N(1/3)

In [31]:
N(1/3, 100)

In [32]:
n50 = N(Rational(1,3), 50)
n50

In [33]:
N(n50, 200)

# Verzweigungen

In [34]:
for n in range(1, 10):
    if n > 2 and n < 5:
        display(n)

In [35]:
for p in range(-3,3):
    for q in range(1, 4):
        r = Rational(p, q)
        if denom(r) != 1:
            display(r)

In [36]:
for j in range(20):
    n = 2**j - 1
    rest = n % 3
    if rest == 0:
        print(f"{n} ist durch 3 teilbar")
    elif rest == 1:
        print(f"{n} lässt bei Division durch 3 den Rest 1")
    else:
        print(f"{n} lässt bei Division durch 3 den Rest 2")

0 ist durch 3 teilbar
1 lässt bei Division durch 3 den Rest 1
3 ist durch 3 teilbar
7 lässt bei Division durch 3 den Rest 1
15 ist durch 3 teilbar
31 lässt bei Division durch 3 den Rest 1
63 ist durch 3 teilbar
127 lässt bei Division durch 3 den Rest 1
255 ist durch 3 teilbar
511 lässt bei Division durch 3 den Rest 1
1023 ist durch 3 teilbar
2047 lässt bei Division durch 3 den Rest 1
4095 ist durch 3 teilbar
8191 lässt bei Division durch 3 den Rest 1
16383 ist durch 3 teilbar
32767 lässt bei Division durch 3 den Rest 1
65535 ist durch 3 teilbar
131071 lässt bei Division durch 3 den Rest 1
262143 ist durch 3 teilbar
524287 lässt bei Division durch 3 den Rest 1


In [41]:
summe = 0
for m in range(1, 1000000):
    if factorial(m) > 1.e100:
        break

m

# Dictionary (assoziativer Speicher), key-value pairs

In [42]:
a = {1: 2, 2: "vier", "vier": 16.}
a

{1: 2, 2: 'vier', 'vier': 16.0}

In [43]:
a[2]

'vier'

In [44]:
a[3]  # KeyError

KeyError: 3

In [45]:
a[3] = 'ix'

In [46]:
a

{1: 2, 2: 'vier', 'vier': 16.0, 3: 'ix'}

In [47]:
quadratzahlen =  {}
for j in range(10):
    quadratzahlen[j] = j**2
    
quadratzahlen

In [48]:
for schluessel in quadratzahlen:
    print(f"Das Quadrat von {schluessel} ist {quadratzahlen[schluessel]}")

Das Quadrat von 0 ist 0
Das Quadrat von 1 ist 1
Das Quadrat von 2 ist 4
Das Quadrat von 3 ist 9
Das Quadrat von 4 ist 16
Das Quadrat von 5 ist 25
Das Quadrat von 6 ist 36
Das Quadrat von 7 ist 49
Das Quadrat von 8 ist 64
Das Quadrat von 9 ist 81


In [49]:
a # Dictionary

{1: 2, 2: 'vier', 'vier': 16.0, 3: 'ix'}

In [50]:
M = {1,2,3,4}  # Menge (engl. set)
M

In [51]:
3 in M

True

In [52]:
5 in M

False

In [53]:
[] # leere Liste
{} # leerer Dictionary

In [54]:
set()   # leere Menge

In [55]:
L = set()
for m in M:
    L.add(m**2)
L

In [56]:
M | L  # Vereinigung

In [57]:
M & L  # Durchschnitt

In [58]:
M - L  # Mengendifferenz

In [59]:
len(M | L)  

# Dictionaries und Substitution

In [60]:
x, y = symbols('x y')

In [61]:
f = exp(-x**2-3*y**3)
f

In [62]:
ersetzung = {x: 2, y: -1}
f.subs(ersetzung)

In [63]:
z = S('z')
g = cos(z)

In [64]:
g.subs({z:x, x:y})

In [65]:
g.subs(z, x).subs(x, y)

# Polynome

In [66]:
p = ((x+1)**4).expand()
p

In [67]:
degree(p, x)

In [68]:
p.coeff(x**2)

In [69]:
p.coeff(x**0)

Das ist der Koeffizient der 1

In [70]:
p.coeff(x, 0)

Den Begriff "Polynom" darf man nicht so wörtlich nehmen

In [71]:
y = S('y')
p = 0
for j in range(6):
    p += (x+j*y + (x+y)*exp(x))**j

p

In [72]:
pe = p.expand()
len(list(pe.args))

In [73]:
pe.collect(exp(x))

In [75]:
pe.collect([exp(x), y])

In [76]:
pe.coeff(x**2*y**3*exp(x))